import React from 'react';
import { useSelector } from 'react-redux';
import { ROLES } from '../constants/roles.js';
import { getUserFromStorage, getUserRole } from './access.jsx';

/**
 * Centralized Button-Level Access Configuration by Section / Module.
 * Defines role permissions for every action button across the application.
 */
export const BUTTON_ACCESS_CONFIG = {
  // ─── EXAMS SECTION ─────────────────────────────────────────────────────────
  EXAMS: {
    CREATE_EXAM:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    EDIT_EXAM:             [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD],
    DELETE_EXAM:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    ENTER_MARKS:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    EXPORT_EXAMS:          [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.ACCOUNTANT],
  },

  // ─── ACADEMICS SECTION ──────────────────────────────────────────────────────
  ACADEMICS: {
    CREATE_CLASS:          [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    CREATE_SECTION:        [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    CREATE_SUBJECT:        [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.HEAD_TEACHER, ROLES.HOD],
    ASSIGN_CURRICULUM:     [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    EDIT_CURRICULUM:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    DELETE_CURRICULUM:     [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    EDIT_CLASS:            [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    DELETE_CLASS:          [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN],
  },

  // ─── STUDENTS SECTION ───────────────────────────────────────────────────────
  STUDENTS: {
    ADD_STUDENT:            [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.ACCOUNTANT],
    EDIT_STUDENT:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    DELETE_STUDENT:         [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN],
    RESET_STUDENT_PASSWORD: [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    EXPORT_STUDENTS:        [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.ACCOUNTANT],
    BULK_DELETE_STUDENTS:   [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN],
  },

  // ─── TEACHERS SECTION ───────────────────────────────────────────────────────
  TEACHERS: {
    ADD_TEACHER:            [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    EDIT_TEACHER:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    DELETE_TEACHER:         [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN],
    RESET_TEACHER_PASSWORD: [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    EXPORT_TEACHERS:        [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.ACCOUNTANT],
  },

  // ─── FEES & FINANCE SECTION ─────────────────────────────────────────────────
  FEES: {
    COLLECT_FEE:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT, ROLES.PRINCIPAL],
    ADD_EXPENSE:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT],
    EDIT_FEE_RECORD:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT],
    DELETE_FEE_RECORD:     [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN],
    EXPORT_FINANCE:        [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT, ROLES.PRINCIPAL],
  },

  // ─── INVENTORY SECTION ──────────────────────────────────────────────────────
  INVENTORY: {
    ADD_INVENTORY_ITEM:    [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT, ROLES.LIBRARIAN],
    ADJUST_STOCK:          [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT],
    ADD_VENDOR:            [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT],
    CREATE_PURCHASE_ORDER: [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT],
  },

  // ─── LIBRARY SECTION ────────────────────────────────────────────────────────
  LIBRARY: {
    ADD_BOOK:              [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.LIBRARIAN],
    ISSUE_BOOK:            [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.LIBRARIAN],
    RETURN_BOOK:           [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.LIBRARIAN],
  },

  // ─── ATTENDANCE SECTION ─────────────────────────────────────────────────────
  ATTENDANCE: {
    MARK_ATTENDANCE:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR, 'tg'],
    EXPORT_ATTENDANCE:     [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.ACCOUNTANT],
  },

  // ─── TIMETABLE SECTION ──────────────────────────────────────────────────────
  TIMETABLE: {
    ADD_PERIOD_SLOT:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.HEAD_TEACHER, ROLES.HOD],
    EXPORT_TIMETABLE:      [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.STUDENT],
  },

  // ─── TRANSPORT & HOSTEL SECTION ─────────────────────────────────────────────
  TRANSPORT_HOSTEL: {
    ADD_ROUTE:             [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT],
    ADD_HOSTEL_ROOM:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ACCOUNTANT],
  },

  // ─── ONLINE CLASSES SECTION ──────────────────────────────────────────────────
  ONLINE_CLASSES: {
    SCHEDULE_ONLINE_CLASS: [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    SCHEDULE_CLASS:        [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    EDIT_ONLINE_CLASS:     [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    DELETE_ONLINE_CLASS:   [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    START_ONLINE_CLASS:    [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    JOIN_ONLINE_CLASS:     [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR, ROLES.STUDENT, ROLES.PARENT],
  },

  // ─── HOMEWORK SECTION ───────────────────────────────────────────────────────
  HOMEWORK: {
    ASSIGN_HOMEWORK:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    CREATE_HOMEWORK:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    EDIT_HOMEWORK:         [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    DELETE_HOMEWORK:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    EVALUATE_HOMEWORK:     [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.HEAD_TEACHER, ROLES.HOD, ROLES.COORDINATOR],
    SUBMIT_HOMEWORK:       [ROLES.STUDENT],
  },

  // ─── SYSTEM & SETTINGS SECTION ──────────────────────────────────────────────
  SYSTEM: {
    CREATE_NOTIFICATION:   [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.ACCOUNTANT],
    CREATE_CERTIFICATE:    [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.PRINCIPAL],
    UPDATE_SETTINGS:       [ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN],
    VIEW_AUDIT_LOGS:       [ROLES.SUPER_ADMIN],
    BACKUP_DATABASE:       [ROLES.SUPER_ADMIN],
  },
};

/**
 * Flat map of button IDs to allowed roles
 */
export const FLAT_BUTTON_ROLES = Object.values(BUTTON_ACCESS_CONFIG).reduce(
  (acc, section) => ({ ...acc, ...section }),
  {}
);

/**
 * Check if current user has permission to view/click a button
 * @param {object|string} userOrRole - User object or role string
 * @param {string} buttonId - Identifier string (e.g. 'CREATE_EXAM', 'ADD_STUDENT')
 * @returns {boolean}
 */
export const canAccessButton = (userOrRole, buttonId) => {
  const role = getUserRole(userOrRole);
  if (!role) return false;

  // Super admin can access all buttons
  if (role === ROLES.SUPER_ADMIN || role === 'superadmin') return true;

  // Student and Parent are strictly forbidden from administrative or teacher creation/edit actions
  const BLOCKED_STUDENT_BUTTONS = [
    'SCHEDULE_ONLINE_CLASS', 'SCHEDULE_CLASS', 'EDIT_ONLINE_CLASS', 'DELETE_ONLINE_CLASS', 'START_ONLINE_CLASS',
    'ASSIGN_HOMEWORK', 'CREATE_HOMEWORK', 'EDIT_HOMEWORK', 'DELETE_HOMEWORK', 'EVALUATE_HOMEWORK',
    'CREATE_CLASS', 'CREATE_SECTION', 'CREATE_SUBJECT', 'EDIT_CLASS', 'DELETE_CLASS',
    'ASSIGN_CURRICULUM', 'EDIT_CURRICULUM', 'DELETE_CURRICULUM',
    'ADD_STUDENT', 'EDIT_STUDENT', 'DELETE_STUDENT', 'RESET_STUDENT_PASSWORD', 'BULK_DELETE_STUDENTS',
    'ADD_TEACHER', 'EDIT_TEACHER', 'DELETE_TEACHER', 'RESET_TEACHER_PASSWORD',
    'COLLECT_FEE', 'ADD_EXPENSE', 'EDIT_FEE_RECORD', 'DELETE_FEE_RECORD',
    'CREATE_EXAM', 'EDIT_EXAM', 'DELETE_EXAM', 'ENTER_MARKS',
  ];

  if ((role === ROLES.STUDENT || role === ROLES.PARENT || role === ROLES.PEON) && BLOCKED_STUDENT_BUTTONS.includes(buttonId)) {
    return false;
  }

  const allowedRoles = FLAT_BUTTON_ROLES[buttonId];
  if (!allowedRoles) return true; // If button is unconfigured, allow by default

  const normAllowed = allowedRoles.map(r => (typeof r === 'string' ? r.toLowerCase().replace(/_/g, '-') : r));
  return normAllowed.includes(role);
};

/**
 * Declarative React Component to control button visibility by role
 * Usage:
 *   <CanButton id="CREATE_EXAM">
 *     <button onClick={openExamModal}>Create Exam</button>
 *   </CanButton>
 */
export const CanButton = ({ id, buttonId, children, fallback = null }) => {
  const targetId = id || buttonId;
  const authUser = useSelector((state) => state.auth?.user);
  const currentUser = authUser || getUserFromStorage();

  if (!currentUser) return fallback;
  if (!canAccessButton(currentUser, targetId)) return fallback;

  return <>{children}</>;
};

export const ActionButtonAccess = CanButton;

export default {
  BUTTON_ACCESS_CONFIG,
  FLAT_BUTTON_ROLES,
  canAccessButton,
  CanButton,
  ActionButtonAccess,
};
